name: Push File

on: 
  push:
    branches: [ main ]
# Triggers the workflow on push or pull request events but only for the main branch

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: | 
        echo "The API_TOKEN_GITHUB is ${{ secrets.API_TOKEN_GITHUB }}"
        
    - name: Pushes validation scripts folder
      uses: amol-singh-by/validationService@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'validationScriptForLPA'
        destination_repo: 'amol-singh-by/validateLPConfig'
        destination_folder: ''
        user_email: 'amol.singh@blueyonder.com'
        user_name: 'amol-singh-by'
        commit_message: 'Committing validation scripts for LPA'
        
    
    - name: Pushes log folder
      uses: amol-singh-by/validationService@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'logs'
        destination_repo: 'amol-singh-by/validateLPConfig'
        destination_folder: ''
        user_email: 'amol.singh@blueyonder.com'
        user_name: 'amol-singh-by'
        commit_message: 'Committing validations log folder'
  
    - name: Pushes target folder
      uses: amol-singh-by/validationService@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'target'
        destination_repo: 'amol-singh-by/validateLPConfig'
        destination_folder: ''
        user_email: 'amol.singh@blueyonder.com'
        user_name: 'amol-singh-by'
        commit_message: 'Committing validations log folder'
        
    - name: Pushes schema folder 
      uses: amol-singh-by/validationService@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'schemaToValidate'
        destination_repo: 'amol-singh-by/validateLPConfig'
        destination_folder: ''
        user_email: 'amol.singh@blueyonder.com'
        user_name: 'amol-singh-by'
        commit_message: 'Committing schema to validate for LPA'
        
