name: Push File

on: 
  push:
    branches: [ main ]
# Triggers the workflow on push or pull request events but only for the main branch

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: | 
        echo "The API_TOKEN_GITHUB is ${{ secrets.API_TOKEN_GITHUB }}"
        
    - name: Pushes test file
      uses: amol-singh-by/validationService@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'validation_standalone.py'
        destination_repo: 'amol-singh-by/validateLPConfig'
        destination_folder: ''
        user_email: 'amol.singh@blueyonder.com'
        user_name: 'amol-singh-by'
        commit_message: 'A custom message for the commit'
        
    
    - name: Pushes test file
      uses: amol-singh-by/validationService@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'log.txt'
        destination_repo: 'amol-singh-by/validateLPConfig'
        destination_folder: ''
        user_email: 'amol.singh@blueyonder.com'
        user_name: 'amol-singh-by'
        commit_message: 'A custom message for the commit'
        
    - name: Pushes test file
      uses: amol-singh-by/validationService@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'deleteLogs.py'
        destination_repo: 'amol-singh-by/validateLPConfig'
        destination_folder: ''
        user_email: 'amol.singh@blueyonder.com'
        user_name: 'amol-singh-by'
        commit_message: 'A custom message for the commit'
        
